version: 2
registries:
  lumi-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.DEPENDABOT_TOKEN}}"
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    labels:
      - "area:deps"
    registries:
      - lumi-packages
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    labels:
      - "area:ci"
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
